services:
  messages-service:
    image: messages-service:${TAG:-latest}
    build:
      context: /root/cent-stage/messages-service
      dockerfile: Dockerfile
      cache_from:
        - messages-service:cache
    env_file:
      - /root/cent-stage/messages-service/.env
    ports:
      - "3007:3007"
    networks:
      - cent-stage-network
    restart: unless-stopped

networks:
  cent-stage-network:
    external: true
